default: &default
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: usersretriever_development
test:
  <<: *default
  database: usersretriever_test
production:
  <<: *default
  database: usersretriever_production
  username: usersretriever
  password: <%= ENV["USERSRETRIEVER_DATABASE_PASSWORD"] %>
